lugares = ['portugal', 'dinamarca', 'noruega', 'alemanha','egito']
print(lugares)
print(sorted(lugares))
print(lugares)
print(sorted(lugares,reverse=1))
print(lugares)
lugares.reverse()
print(lugares)
lugares.reverse()
print(lugares)
lugares.sort()
print(lugares)
lugares.sort(reverse=1)
print(lugares)

